### ISSUE TITLE
What's the difference between git.build.version and git.commit.id.describe? 

### ISSUE THREAD

**Issue by darioseidl** [n0mer/gradle-git-properties#119]
Hello!

I have a project using this plugin, it generates a `git.properties` file containing:
```
git.build.version=v0.3.0-26-g3ec4a04
git.closest.tag.commit.count=30
git.closest.tag.name=v0.3.0
git.commit.id=3ec4a04e9dde1f1f879bca9ff5c282f3e66e8d36
git.commit.id.abbrev=3ec4a04
git.commit.id.describe=v0.3.0-30-g3ec4a04
```
I always assumed that the second part of `git.build.version` is the closest commit count, but apparently it's not. What is the 26 referring to here? Is there a way to make the `git.build.version` the same as `git.commit.id.describe`?

**Comment by tha2015** [comment]
git.build.version property is supposed to be the project.version of Gradle project.

In this case, it seems like you are using another plugin (https://github.com/palantir/gradle-git-version) to set project version to a "git-describe" value. The problem is is "gradle-git-version" plugin uses git-describe command with different options (comparing to the way "gradle-git-properties" plugin is generating "git.commit.id.describe" property, which uses default options).

It will depend on which value do you want to use. If you want the git-describe with default options, you should replace "gradle-git-version" plugin by "grgit" plugin. I believe that project.version could be set to value of grgit.describe(). Otherwise, if you want to use value from "gradle-git-version" plugin, you could use 
``customProperty 'git.build.version', { project.version }
``
