### ISSUE TITLE
Git warnings in logs after updating to 2.0.0

### ISSUE THREAD

**Issue by ctmay4** [n0mer/gradle-git-properties#125]
I've been using the plugin for quite a while and recently updated to 2.0.0.  All our CI builds now how the following warning:

```
[09:47:14][Step 1/1] Exception caught during execution of command '[git, config, --system, --edit]' in '/usr/local/git/bin', return code '128', error message 'fatal: Could not switch to '/usr/local/git-2.6.3/etc/': No such file or directory
[09:47:14][Step 1/1] '
```

Everything still seems to work correctly.  I researched this a bit online and it seems to be related to the JGit dependency update in 2.0.0.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=476639

For now I've just rolled back to 1.5.2 to get rid of the log messages since everything was working fine.

**Comment by tha2015** [comment]
Thanks @ctmay4 . 

Analysis:

The message comes from jgit:5.1.3.201810200350-r which is being used by the plugin.

```
gradle-git-properties:20.0.0
+--- org.ajoberstar.grgit:grgit-core:3.0.0
|    \--- org.eclipse.jgit:org.eclipse.jgit:5.1.3.201810200350-r
```
Source code: for [jgit 5.1.3](https://repo.eclipse.org/content/groups/releases/org/eclipse/jgit/org.eclipse.jgit/5.1.3.201810200350-r/org.eclipse.jgit-5.1.3.201810200350-r-sources.jar)

JGit issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=476639#c14 (I added comment 14)

Workaround: Until the issue is fixed in newer jgit versions, we can workaround by creating the missing directory or avoid using native git

**Comment by ctmay4** [comment]
Thanks for looking at this.  Our CI servers are indeed using a very old version of Git (2.6.3 released in Nov 2015).  I requested that it be updated and for now I have just downgraded to 1.5.2 to hide the warning.  

I think this should be closed now.
