### ISSUE TITLE
dotGitDir is incorrectly set under Java 11 in a git hook

### ISSUE THREAD

**Issue by mernst** [n0mer/gradle-git-properties#144]
When I run `gradle generateGitProperties` from a git hook under Java 11, it sets `dotGitDirectory` to `$HOME/.gradle/daemon/6.1.1/.git` and fails.

Here is how to reproduce the problem:

```
cd ~/tmp
rm -rf randoop
git clone --depth 1 https://github.com/randoop/randoop.git
cd randoop
sed -i 's/dotGitDirectory/\/\/ dotGitDirectory/' build.gradle
sed -i 's/^.\/gradlew.*/.\/gradlew --debug -s generateGitProperties/' scripts/pre-commit
./gradlew installGitHooks

touch dummy-file.txt
git add dummy-file.txt
git commit -m "Dummy file"
```

When I run the above commands under Java 8, the commit succeeds.
When I run them under Java 11, they fail with 

```
Execution failed for task ':generateGitProperties'.
org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /scratch/mernst/.gradle/daemon/6.1.1/.git
```

I can work around this by setting `dotGitDirectory` in my `build.gradle`, but it would be nicer to change the plugin to fix the problem.

**Comment by tha2015** [comment]
Thanks @mernst  for the detailed information. I will check and fix it soon.

**Comment by tha2015** [comment]
Hi @mernst 

I could not reproduce the issue, the file git.properties was created correctly at tmp/randoop/build/resources/main/

My environment: OpenJDK 11.0.6+10 / Ubuntu 19.10

I notice that you are running the task with -debug flag. The plugin should have printed some useful info which might be useful to figure out the root cause. For example, you can find some info using below command:
`
git commit -m "Dummy file" 2>&1 | grep -i git
`

Thanks,
-Thai

**Comment by mernst** [comment]
My apologies for submitting a bug report that you cannot reproduce.
It's still happening on my end, but not on all operating systems.
In particular, the problem occurs on Centos 7.7 but not on Ubuntu 19.10.

Here is information for a computer on which the problem occurs:

```
% uname -a
Linux godwit.cs.washington.edu 4.14.158-1.el7.retpoline.x86_64 #1 SMP Thu Dec 5 14:07:28 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
% lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.7.1908 (Core)
Release:	7.7.1908
Codename:	Core
% java -version
openjdk version "11.0.6" 2020-01-14 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.6+10-LTS, mixed mode, sharing)
```

I have attached the log of the `git commit` command, on the CentOS computer where the problem occurs.

[git-commit-output.txt](https://github.com/n0mer/gradle-git-properties/files/4226140/git-commit-output.txt)

**Comment by tha2015** [comment]
Thanks @mernst . From the log file, it looks like something wrong happened when the plugin trying to detect git repository directory for the project. I will check on CentOS and let you know the root cause soon.

**Comment by tha2015** [comment]
I could reproduce the issue on CentOS 7. Thanks for your information. It looks like the issue is related to current directory when git executing the hook. I will debug more to see why it is different to Ubuntu

**Comment by tha2015** [comment]
New update: The issue is caused by changes in Java 11 regarding preventing setting working directory (user.dir) while Gradle depends on it to do different things (for example, the initial working directory was "randoop" and Gradle tried to change it to "daemon/6.1.1" but the initial value was still leftover somewhere and although they tried to fix it, see this issue https://github.com/gradle/gradle/issues/7323 ). As a result, when Grgit resolving relative path ".git" received from JGit, it resolved to a wrong (absolute) location. I'm not sure why this issue happens only on CentOS and not on Ubuntu. I will debug on Ubuntu to compare the results.

**Comment by tha2015** [comment]
Issue is now fixed in v2.2.2 (just published)

FYI I also opened a issue https://github.com/gradle/native-platform/issues/113 for Gradle team regarding this

**Comment by mernst** [comment]
I confirm that this corrects the problem.  Thanks for the fix!

**Comment by tha2015** [comment]
Thanks
